### ISSUE TITLE
Smoke test failure: ValueError: invalid literal for int() with base 10: '<path:pk>'

### ISSUE THREAD

**Issue by jayvdb** [jyveapp/django-action-framework#14]
django-smoke-tests is a bit hard to set up - I needed to use their master, and patch it, but it provides good results and I have it running in CI with a few "exclude" rules, mostly for apps which are misbehaving or are not checking their input before using it on the database.

I run it with `--allow-status-codes 200,201,301,302,304,400,405,415` , as that seems to encompass most codes that apps should emit.  It does not use invalid legal data, which would require the addition of 404.  It only uses valid data , or invalid+illegal data .  In this case it is actually a bug(feature?) in the smoke tester putting an invalid url arg `<path:pk>` literally into the URL.  It happens to be quite a useful bug, as it shows when insufficient checking of URL args is occurring.

The URL arg should be sanity checked before using it on the database, or at least db exceptions should be caught and a 400 Bad Request response returned.  It should be a server error (5xx) if the server can reliably know that the client provided an identifier for a requested object is of the wrong datatype.  5xx need rather urgent investigation by the operational team , whereas 400 Bad Request only need regular spot checking to ensure that the cause is bad actors being blocked and it isnt the frontend JS app which is misbehaving, if there is a separate frontend.

Quite possibly in addition to sanity checking, `<path:pk>` should be `<int:pk>` for most models, falling back to `<path:pk>` only if the type of the primary key is not the default.

```py
======================================================================
ERROR: test_smoke_POST_admin/order/order/<path:pk>/object-action/my-action-name/ (django_smoke_tests.tests.SmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/django-smoke-tests/django_smoke_tests/generator.py", line 90, in test
    response = http_method_function(url, {})
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 357, in post
    secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/daf/admin.py", line 155, in wrapper
    return admin.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/djarg/views.py", line 114, in post
    self.object = self.get_object()
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/detail.py", line 36, in get_object
    queryset = queryset.filter(pk=pk)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 972, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '<path:pk>'
```

**Comment by jayvdb** [comment]
I also get this when using schemathesis with the DAF DRF actions.
